# This is a basic workflow to help you get started with Actions

name: Weekly Sync

# Controls when the workflow will run
on:
  schedule:
   - cron: '30 9 * * *' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_issue:
    name: Create weekly team update issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@v2
        with:
          assignees: "gsamant"
          labels: "weekly update"
          title: "Weekly Update"
          body: |
            ### Agenda

            - [ ] Accomplishemnts
            - [ ] Insights
            - [ ] Blockers
            - [ ] Upcoming week
                    
          pinned: true
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
